### ISSUE TITLE
Svg element with class "peel-svg-clip-element" not clearing on component unmount

### ISSUE THREAD

**Issue by pauguri** [iqbal-rashed/react-peel#1]
### Describe the bug

When the `<PeelWrapper> ... </PeelWrapper>` component is rendered, it creates a `<svg>` element outside the body:

![Captura de pantalla 2024-05-17 a les 16 19 28](https://github.com/iqbal-rashed/react-peel/assets/29796354/8f2fba46-92aa-4a0c-b0fd-cb083601925e)

the issue is that this element does not disappear when the component is unmounted/unloaded, which causes it to accumulate when multiple Peel components are loaded one after the other.

![image](https://github.com/iqbal-rashed/react-peel/assets/29796354/abf2c24e-0ae8-4e83-bb7b-f8041db323a1)

This also causes that `<svg>` element to lose its style and become not absolutely positioned, which leaves a blank space on the page.

### Expected behavior

When unmounting the `<PeelWrapper> ... </PeelWrapper>` component, the `<svg class="peel-svg-clip-element"> ... </svg>` element should disappear.

### Validations

- [X] Check if you're on the [latest React-Peel version](https://github.com/iqbal-rashed/react-peel/releases/latest).
- [X] Read the [docs](https://react-peel.vercel.app).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by iqbal-rashed** [comment]
Fixed the issue

**Comment by iqbal-rashed** [comment]
Fixed the issue
